// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloservice.proto

package com.grpc.server.service.hello;

public final class HelloServiceImpl {
  private HelloServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_service_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_service_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_service_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_service_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022helloservice.proto\022\035com.grpc.server.se" +
      "rvice.hello\"3\n\014HelloRequest\022\021\n\tfirstName" +
      "\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\"!\n\rHelloRespons" +
      "e\022\020\n\010greeting\030\001 \001(\t2r\n\014HelloService\022b\n\005h" +
      "ello\022+.com.grpc.server.service.hello.Hel" +
      "loRequest\032,.com.grpc.server.service.hell" +
      "o.HelloResponseB\024B\020HelloServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_server_service_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_server_service_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_service_hello_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_grpc_server_service_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_server_service_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_service_hello_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
