// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloservice.proto

package com.grpc.server.service.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.server.service.hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string greeting = 1;</code>
   */
  java.lang.String getGreeting();
  /**
   * <code>optional string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
