package com.grpc.server.service;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   */
  String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
