// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WalletService.proto

package com.grpc.server.wallet;

/**
 * Protobuf type {@code com.grpc.server.wallet.TransactionRequest}
 */
public  final class TransactionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.grpc.server.wallet.TransactionRequest)
    TransactionRequestOrBuilder {
  // Use TransactionRequest.newBuilder() to construct.
  private TransactionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransactionRequest() {
    addressFrom_ = "";
    passwordFrom_ = "";
    addressTo_ = "";
    value_ = 0L;
    commission_ = 0L;
    timeout_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TransactionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            addressFrom_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            passwordFrom_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            addressTo_ = s;
            break;
          }
          case 32: {

            value_ = input.readInt64();
            break;
          }
          case 40: {

            commission_ = input.readInt64();
            break;
          }
          case 48: {

            timeout_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.server.wallet.WalletSevice.internal_static_com_grpc_server_wallet_TransactionRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.server.wallet.WalletSevice.internal_static_com_grpc_server_wallet_TransactionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.server.wallet.TransactionRequest.class, com.grpc.server.wallet.TransactionRequest.Builder.class);
  }

  public static final int ADDRESSFROM_FIELD_NUMBER = 1;
  private volatile java.lang.Object addressFrom_;
  /**
   * <code>optional string addressFrom = 1;</code>
   */
  public java.lang.String getAddressFrom() {
    java.lang.Object ref = addressFrom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addressFrom_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addressFrom = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAddressFromBytes() {
    java.lang.Object ref = addressFrom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addressFrom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORDFROM_FIELD_NUMBER = 2;
  private volatile java.lang.Object passwordFrom_;
  /**
   * <code>optional string passwordFrom = 2;</code>
   */
  public java.lang.String getPasswordFrom() {
    java.lang.Object ref = passwordFrom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passwordFrom_ = s;
      return s;
    }
  }
  /**
   * <code>optional string passwordFrom = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordFromBytes() {
    java.lang.Object ref = passwordFrom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passwordFrom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESSTO_FIELD_NUMBER = 3;
  private volatile java.lang.Object addressTo_;
  /**
   * <code>optional string addressTo = 3;</code>
   */
  public java.lang.String getAddressTo() {
    java.lang.Object ref = addressTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      addressTo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string addressTo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAddressToBytes() {
    java.lang.Object ref = addressTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      addressTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 4;
  private long value_;
  /**
   * <code>optional int64 value = 4;</code>
   */
  public long getValue() {
    return value_;
  }

  public static final int COMMISSION_FIELD_NUMBER = 5;
  private long commission_;
  /**
   * <code>optional int64 commission = 5;</code>
   */
  public long getCommission() {
    return commission_;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 6;
  private long timeout_;
  /**
   * <code>optional int64 timeout = 6;</code>
   */
  public long getTimeout() {
    return timeout_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressFrom_);
    }
    if (!getPasswordFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passwordFrom_);
    }
    if (!getAddressToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, addressTo_);
    }
    if (value_ != 0L) {
      output.writeInt64(4, value_);
    }
    if (commission_ != 0L) {
      output.writeInt64(5, commission_);
    }
    if (timeout_ != 0L) {
      output.writeInt64(6, timeout_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressFrom_);
    }
    if (!getPasswordFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passwordFrom_);
    }
    if (!getAddressToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, addressTo_);
    }
    if (value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, value_);
    }
    if (commission_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, commission_);
    }
    if (timeout_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timeout_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.server.wallet.TransactionRequest)) {
      return super.equals(obj);
    }
    com.grpc.server.wallet.TransactionRequest other = (com.grpc.server.wallet.TransactionRequest) obj;

    boolean result = true;
    result = result && getAddressFrom()
        .equals(other.getAddressFrom());
    result = result && getPasswordFrom()
        .equals(other.getPasswordFrom());
    result = result && getAddressTo()
        .equals(other.getAddressTo());
    result = result && (getValue()
        == other.getValue());
    result = result && (getCommission()
        == other.getCommission());
    result = result && (getTimeout()
        == other.getTimeout());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ADDRESSFROM_FIELD_NUMBER;
    hash = (53 * hash) + getAddressFrom().hashCode();
    hash = (37 * hash) + PASSWORDFROM_FIELD_NUMBER;
    hash = (53 * hash) + getPasswordFrom().hashCode();
    hash = (37 * hash) + ADDRESSTO_FIELD_NUMBER;
    hash = (53 * hash) + getAddressTo().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValue());
    hash = (37 * hash) + COMMISSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommission());
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeout());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.server.wallet.TransactionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.server.wallet.TransactionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.server.wallet.TransactionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.server.wallet.TransactionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.grpc.server.wallet.TransactionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.grpc.server.wallet.TransactionRequest)
      com.grpc.server.wallet.TransactionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.server.wallet.WalletSevice.internal_static_com_grpc_server_wallet_TransactionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.server.wallet.WalletSevice.internal_static_com_grpc_server_wallet_TransactionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.server.wallet.TransactionRequest.class, com.grpc.server.wallet.TransactionRequest.Builder.class);
    }

    // Construct using com.grpc.server.wallet.TransactionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      addressFrom_ = "";

      passwordFrom_ = "";

      addressTo_ = "";

      value_ = 0L;

      commission_ = 0L;

      timeout_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.server.wallet.WalletSevice.internal_static_com_grpc_server_wallet_TransactionRequest_descriptor;
    }

    public com.grpc.server.wallet.TransactionRequest getDefaultInstanceForType() {
      return com.grpc.server.wallet.TransactionRequest.getDefaultInstance();
    }

    public com.grpc.server.wallet.TransactionRequest build() {
      com.grpc.server.wallet.TransactionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.grpc.server.wallet.TransactionRequest buildPartial() {
      com.grpc.server.wallet.TransactionRequest result = new com.grpc.server.wallet.TransactionRequest(this);
      result.addressFrom_ = addressFrom_;
      result.passwordFrom_ = passwordFrom_;
      result.addressTo_ = addressTo_;
      result.value_ = value_;
      result.commission_ = commission_;
      result.timeout_ = timeout_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.server.wallet.TransactionRequest) {
        return mergeFrom((com.grpc.server.wallet.TransactionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.server.wallet.TransactionRequest other) {
      if (other == com.grpc.server.wallet.TransactionRequest.getDefaultInstance()) return this;
      if (!other.getAddressFrom().isEmpty()) {
        addressFrom_ = other.addressFrom_;
        onChanged();
      }
      if (!other.getPasswordFrom().isEmpty()) {
        passwordFrom_ = other.passwordFrom_;
        onChanged();
      }
      if (!other.getAddressTo().isEmpty()) {
        addressTo_ = other.addressTo_;
        onChanged();
      }
      if (other.getValue() != 0L) {
        setValue(other.getValue());
      }
      if (other.getCommission() != 0L) {
        setCommission(other.getCommission());
      }
      if (other.getTimeout() != 0L) {
        setTimeout(other.getTimeout());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.server.wallet.TransactionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.server.wallet.TransactionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object addressFrom_ = "";
    /**
     * <code>optional string addressFrom = 1;</code>
     */
    public java.lang.String getAddressFrom() {
      java.lang.Object ref = addressFrom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressFrom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string addressFrom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressFromBytes() {
      java.lang.Object ref = addressFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addressFrom = 1;</code>
     */
    public Builder setAddressFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addressFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addressFrom = 1;</code>
     */
    public Builder clearAddressFrom() {
      
      addressFrom_ = getDefaultInstance().getAddressFrom();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addressFrom = 1;</code>
     */
    public Builder setAddressFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addressFrom_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object passwordFrom_ = "";
    /**
     * <code>optional string passwordFrom = 2;</code>
     */
    public java.lang.String getPasswordFrom() {
      java.lang.Object ref = passwordFrom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passwordFrom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string passwordFrom = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordFromBytes() {
      java.lang.Object ref = passwordFrom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwordFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string passwordFrom = 2;</code>
     */
    public Builder setPasswordFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passwordFrom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string passwordFrom = 2;</code>
     */
    public Builder clearPasswordFrom() {
      
      passwordFrom_ = getDefaultInstance().getPasswordFrom();
      onChanged();
      return this;
    }
    /**
     * <code>optional string passwordFrom = 2;</code>
     */
    public Builder setPasswordFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passwordFrom_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object addressTo_ = "";
    /**
     * <code>optional string addressTo = 3;</code>
     */
    public java.lang.String getAddressTo() {
      java.lang.Object ref = addressTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string addressTo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressToBytes() {
      java.lang.Object ref = addressTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string addressTo = 3;</code>
     */
    public Builder setAddressTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      addressTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string addressTo = 3;</code>
     */
    public Builder clearAddressTo() {
      
      addressTo_ = getDefaultInstance().getAddressTo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string addressTo = 3;</code>
     */
    public Builder setAddressToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      addressTo_ = value;
      onChanged();
      return this;
    }

    private long value_ ;
    /**
     * <code>optional int64 value = 4;</code>
     */
    public long getValue() {
      return value_;
    }
    /**
     * <code>optional int64 value = 4;</code>
     */
    public Builder setValue(long value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 value = 4;</code>
     */
    public Builder clearValue() {
      
      value_ = 0L;
      onChanged();
      return this;
    }

    private long commission_ ;
    /**
     * <code>optional int64 commission = 5;</code>
     */
    public long getCommission() {
      return commission_;
    }
    /**
     * <code>optional int64 commission = 5;</code>
     */
    public Builder setCommission(long value) {
      
      commission_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 commission = 5;</code>
     */
    public Builder clearCommission() {
      
      commission_ = 0L;
      onChanged();
      return this;
    }

    private long timeout_ ;
    /**
     * <code>optional int64 timeout = 6;</code>
     */
    public long getTimeout() {
      return timeout_;
    }
    /**
     * <code>optional int64 timeout = 6;</code>
     */
    public Builder setTimeout(long value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 timeout = 6;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.grpc.server.wallet.TransactionRequest)
  }

  // @@protoc_insertion_point(class_scope:com.grpc.server.wallet.TransactionRequest)
  private static final com.grpc.server.wallet.TransactionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.server.wallet.TransactionRequest();
  }

  public static com.grpc.server.wallet.TransactionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransactionRequest>
      PARSER = new com.google.protobuf.AbstractParser<TransactionRequest>() {
    public TransactionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransactionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransactionRequest> getParserForType() {
    return PARSER;
  }

  public com.grpc.server.wallet.TransactionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

