// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WalletService.proto

package com.grpc.server.wallet;

public interface TransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.server.wallet.TransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string addressFrom = 1;</code>
   */
  java.lang.String getAddressFrom();
  /**
   * <code>optional string addressFrom = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressFromBytes();

  /**
   * <code>optional string passwordFrom = 2;</code>
   */
  java.lang.String getPasswordFrom();
  /**
   * <code>optional string passwordFrom = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordFromBytes();

  /**
   * <code>optional string addressTo = 3;</code>
   */
  java.lang.String getAddressTo();
  /**
   * <code>optional string addressTo = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressToBytes();

  /**
   * <code>optional int64 value = 4;</code>
   */
  long getValue();

  /**
   * <code>optional int64 commission = 5;</code>
   */
  long getCommission();

  /**
   * <code>optional int64 timeout = 6;</code>
   */
  long getTimeout();
}
