// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WalletService.proto

package com.grpc.server.wallet;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.server.wallet.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>optional string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>optional string addressWallet = 3;</code>
   */
  java.lang.String getAddressWallet();
  /**
   * <code>optional string addressWallet = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressWalletBytes();
}
