// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WalletService.proto

package com.grpc.server.wallet;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.server.wallet.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>optional string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>optional string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
