// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WalletService.proto

package com.grpc.server.wallet;

public final class WalletSevice {
  private WalletSevice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_wallet_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_wallet_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_wallet_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_wallet_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_wallet_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_wallet_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_server_wallet_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_server_wallet_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/WalletService.proto\022\026co" +
      "m.grpc.server.wallet\".\n\013UserRequest\022\r\n\005l" +
      "ogin\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"F\n\014UserResp" +
      "onse\022\r\n\005login\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\025\n" +
      "\raddressWallet\030\003 \001(\t\"\206\001\n\022TransactionRequ" +
      "est\022\023\n\013addressFrom\030\001 \001(\t\022\024\n\014passwordFrom" +
      "\030\002 \001(\t\022\021\n\taddressTo\030\003 \001(\t\022\r\n\005value\030\004 \001(\003" +
      "\022\022\n\ncommission\030\005 \001(\003\022\017\n\007timeout\030\006 \001(\003\"M\n" +
      "\023TransactionResponse\022\020\n\010userFrom\030\001 \001(\t\022\024" +
      "\n\014passwordFrom\030\002 \001(\t\022\016\n\006userTo\030\003 \001(\t2\325\001\n",
      "\rWalletService\022Y\n\014createWallet\022#.com.grp" +
      "c.server.wallet.UserRequest\032$.com.grpc.s" +
      "erver.wallet.UserResponse\022i\n\016setTransact" +
      "ion\022*.com.grpc.server.wallet.Transaction" +
      "Request\032+.com.grpc.server.wallet.Transac" +
      "tionResponseB\020B\014WalletSeviceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_server_wallet_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_server_wallet_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_wallet_UserRequest_descriptor,
        new java.lang.String[] { "Login", "Password", });
    internal_static_com_grpc_server_wallet_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_server_wallet_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_wallet_UserResponse_descriptor,
        new java.lang.String[] { "Login", "Password", "AddressWallet", });
    internal_static_com_grpc_server_wallet_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_server_wallet_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_wallet_TransactionRequest_descriptor,
        new java.lang.String[] { "AddressFrom", "PasswordFrom", "AddressTo", "Value", "Commission", "Timeout", });
    internal_static_com_grpc_server_wallet_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpc_server_wallet_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_server_wallet_TransactionResponse_descriptor,
        new java.lang.String[] { "UserFrom", "PasswordFrom", "UserTo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
