// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.grpc.server.google.proto;

public final class AddressBookClass {
  private AddressBookClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Books_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Books_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\"\243\001\n\004Book\022\020\n\010userName" +
      "\030\001 \001(\t\022\020\n\010nameBook\030\002 \001(\t\022\031\n\007address\030\003 \001(" +
      "\0132\010.Address\022\016\n\006author\030\004 \001(\t\022 \n\010bookType\030" +
      "\005 \001(\0162\016.Book.BookType\"*\n\010BookType\022\n\n\006MOB" +
      "ILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"8\n\007Address\022\017\n\007" +
      "country\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\016\n\006street\030\003 " +
      "\001(\t\"\030\n\004User\022\020\n\010userName\030\001 \001(\t\"\"\n\005Books\022\031" +
      "\n\narrayBooks\030\001 \003(\0132\005.Book2S\n\013AddressBook" +
      "\022#\n\020getAddressByBook\022\005.Book\032\010.Address\022\037\n" +
      "\016getBooksByUser\022\005.User\032\006.BooksB2\n\034com.gr",
      "pc.server.google.protoB\020AddressBookClass" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Book_descriptor,
        new java.lang.String[] { "UserName", "NameBook", "Address", "Author", "BookType", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Country", "City", "Street", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_Books_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Books_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Books_descriptor,
        new java.lang.String[] { "ArrayBooks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
