// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.grpc.server.google.proto;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string country = 1;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>optional string country = 1;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>optional string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>optional string street = 3;</code>
   */
  java.lang.String getStreet();
  /**
   * <code>optional string street = 3;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();
}
