// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.grpc.server.google.proto;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>optional string nameBook = 2;</code>
   */
  java.lang.String getNameBook();
  /**
   * <code>optional string nameBook = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBookBytes();

  /**
   * <code>optional .Address address = 3;</code>
   */
  boolean hasAddress();
  /**
   * <code>optional .Address address = 3;</code>
   */
  com.grpc.server.google.proto.Address getAddress();
  /**
   * <code>optional .Address address = 3;</code>
   */
  com.grpc.server.google.proto.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>optional string author = 4;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>optional string author = 4;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>optional .Book.BookType bookType = 5;</code>
   */
  int getBookTypeValue();
  /**
   * <code>optional .Book.BookType bookType = 5;</code>
   */
  com.grpc.server.google.proto.Book.BookType getBookType();
}
