// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.grpc.server.google.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
